### ISSUE TITLE
Application side hash does not match with server side one for reservations.

### ISSUE THREAD

**Issue by NedelcuRadu** [NoWorryParking/Coding#22]

**Comment by NedelcuRadu** [comment]
Test url: http://noworryparking.online/reservation.php?&zi=10&luna=6&an=2021&ora=17&min=20&nrore=2&email=radu.ndlcu%40gmail.com&idParcare=ChIJb1mq1Ar_sUAR6-kW0mNXBFg&hash=15eedd9af34638699a1f6dad7ee318e9

**Comment by iuga-paula** [comment]
Am la hash doar email si secretKey se pare ca nu lua bine zi/luna/an
